'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class editable_grid

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''CurrentOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentOrder As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''ReportsPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportsPage As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''RadGridReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridReports As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''BannersPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BannersPage As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''RadGridBanners control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridBanners As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''StubsPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StubsPage As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''RadGridStubs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridStubs As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pageImportExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageImportExport As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''legendText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents legendText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''chkReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReports As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkBanners control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBanners As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkStubs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStubs As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NewReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewReport As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblTableID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTableID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeliverableID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeliverableID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductInstanceName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductInstanceName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTopN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopN As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtReportTableNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReportTableNo As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtReportName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReportName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReportFooter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReportFooter1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReportFooter2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReportFooter2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReportFooter3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReportFooter3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MKTSEG_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MKTSEG_Name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''MSValueHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MSValueHolder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtMSDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMSDisplay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRankType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRankType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSortYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSortYear As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtStubID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStubID As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''Table_Type_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_Type_No As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Table_Average_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_Average_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Table_Average_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_Average_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Table_Average_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_Average_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTableBannerHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTableBannerHeight As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtUniqueID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUniqueID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGroupID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGroupID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGroupName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NewBanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewBanner As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblBannerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBannerID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBannerDeliverableID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBannerDeliverableID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBannerProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBannerProductID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBannerProductInstanceName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBannerProductInstanceName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''banner_report_table_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents banner_report_table_no As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBannerDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBannerDisplay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOrderBanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderBanner As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtNumOfYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumOfYears As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtSuperHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSuperHeader As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Source_System_Trend_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Source_System_Trend_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DRA_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DRA_Name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DRAValueHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DRAValueHolder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIndicator As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Numerator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Numerator As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Denominator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Denominator As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Number_Format control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Number_Format As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Decimals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Decimals As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtControlColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtControlColumn As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtObjectIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObjectIndicator As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstFormatType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstFormatType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnBannerSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBannerSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBannerDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBannerDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBannerCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBannerCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NewStub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewStub As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblReportStubID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportStubID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStubDeliverableID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStubDeliverableID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Stub_Stub_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stub_Stub_ID As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''dra_attr_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dra_attr_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DRAAttrValueHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DRAAttrValueHolder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSortAttrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSortAttrName As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtSortAttrValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSortAttrValue As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtAttrNameOverride control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttrNameOverride As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAttr_Value_Override control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttr_Value_Override As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stub_Super_Header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stub_Super_Header As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNameValueFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameValueFlag As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stub_Control_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stub_Control_Number As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''lstFormatType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstFormatType2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnStubSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStubSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnStubDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStubDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnStubCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStubCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ResortReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResortReports As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''radTreeResort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radTreeResort As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''btnSortReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSortReports As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnResortCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResortCancel As Global.System.Web.UI.WebControls.Button
End Class
